// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1izB9Abud6Tm2eepsrg9818t2rRnYPMA',
    appId: '1:270834648403:web:2aac176fdba15371454da6',
    messagingSenderId: '270834648403',
    projectId: 'confrennce-room',
    authDomain: 'confrennce-room.firebaseapp.com',
    storageBucket: 'confrennce-room.firebasestorage.app',
    measurementId: 'G-GXB7GHY3XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBazzUdrr0-L5oq0M44aKEyYZs2ctNYW3M',
    appId: '1:270834648403:android:613028a4a0918584454da6',
    messagingSenderId: '270834648403',
    projectId: 'confrennce-room',
    storageBucket: 'confrennce-room.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1izB9Abud6Tm2eepsrg9818t2rRnYPMA',
    appId: '1:270834648403:web:33775b17570a89eb454da6',
    messagingSenderId: '270834648403',
    projectId: 'confrennce-room',
    authDomain: 'confrennce-room.firebaseapp.com',
    storageBucket: 'confrennce-room.firebasestorage.app',
    measurementId: 'G-M6ZEGWNCTC',
  );
}
